version: "3"
services:
  backend:
    image: "counter-app-backend"
    build: .
    environment:
      - MONGODB_URL=mongodb://mongo:27017/counters
      - PORT=5000
    command: sh -c "sleep 10 && npm run createDB && npm start"
    ports:
      - "5000:5000"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
